include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - generateSchedule
  - runTraining

# image and mounts
variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/nettest:$CI_COMMIT_SHA
  CSCS_ADDITIONAL_MOUNTS: '["/iopsstor/scratch/cscs/vjoost/nettest/data:/workspace/data", "/capstor/scratch/cscs/vjoost/nettest/scratch/:/workspace/scratch/"]'

# build the container image
build:
  stage: build
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

# generate the schedule to be executed in a child pipeline
generateSchedule:
  timeout: 24h
  stage: generateSchedule
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - /workspace/nettest/do_generate_schedule.sh > $CI_PROJECT_DIR/training_schedule.yml
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '00:30:00'
  artifacts:
    paths:
      - training_schedule.yml

# run the training according to the previously generated schedule
runTraining:
  stage: runTraining
  needs: [generateSchedule]
  trigger:
    include:
      - artifact: training_schedule.yml
        job: generateSchedule
    forward:
      pipeline_variables: true
    strategy: depend
