include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test1
  - test2

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/helloworld:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

test1_job:
  stage: test1
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - ./Stockfish/src/stockfish speedtest
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '01:00:00'
    CSCS_ADDITIONAL_MOUNTS: '["/iopsstor/scratch/cscs/vjoost/data:/workspace/data"]'

test2_job:
  stage: test2
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - cd nnue-pytorch && python train.py /workspace/data/dfrc_n5000.binpack --threads 16 --num-workers 16 --batch-size 16384 --random-fen-skipping 3 --features=HalfKAv2_hm^ --max_epochs=3 --default_root_dir ./training/runs/run_0 --gpus="0,"
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '01:00:00'
    CSCS_ADDITIONAL_MOUNTS: '["/iopsstor/scratch/cscs/vjoost/data:/workspace/data"]'
