include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - ensureDataAndSchedule
  - runTraining
  - runMatch

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/nettest:$CI_COMMIT_SHA
  CSCS_ADDITIONAL_MOUNTS: '["/iopsstor/scratch/cscs/vjoost/nettest/data:/workspace/data", "/capstor/scratch/cscs/vjoost/nettest/scratch/:/workspace/scratch/"]'

build_job:
  stage: build
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/docker/Dockerfile.build

# ensure data is in place
ensureDataAndSchedule:
  timeout: 48h
  stage: ensureDataAndSchedule
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test60
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test77
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test78
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test79
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test80-2022
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test80-2023
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock test80-2024
    - /workspace/nettest/do_ensure_data.sh /workspace/data linrock dual-nnue
    - /workspace/nettest/do_ensure_data.sh /workspace/data official-stockfish master-binpacks
    - /workspace/nettest/do_ensure_data.sh /workspace/data official-stockfish master-smallnet-binpacks
    - /workspace/nettest/do_generate_schedule.sh > $CI_PROJECT_DIR/training_schedule.yml
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '04:00:00'
  artifacts:
    paths:
      - training_schedule.yml

# run the training according to the previously generated schedule
runTraining:
  stage: runTraining
  needs: [ensureDataAndSchedule]
  trigger:
    include:
      - artifact: training_schedule.yml
        job: ensureDataAndSchedule
    forward:
      pipeline_variables: true
    strategy: depend

# A final test with a match
runMatch:
  timeout: 48h
  stage: runMatch
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - /workspace/nettest/do_run_match.sh $CI_PROJECT_DIR/networks/ /workspace/scratch/$CI_COMMIT_SHA/match 600
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '04:00:00'
